### ISSUE TITLE
Фильтрация в query для значений null / undefined

### ISSUE THREAD

**Issue by dj-stormtrooper** [pasaran/descript3#1]
Для блоков вида:

```js
const block = de.object({
  block: {
    query: () => ({ foo: undefined })
  },
})
```

Сейчас генерируется querystring вида `?foo=`

Выглядит более логичным и совместимым с descript2 вариант, когда проп со значением undefined исключается из запроса. Можно такую же логику оставить для null

Пока не встречал живого кейса, где актуально было бы честно передавать пустой проп, для таких кейсов можно явно передать `{ prop: "" }`

Что думаешь?

**Comment by pasaran** [comment]
Да, я тоже думал про это. Там даже частично фильтруется, если query задано объектом. Вроде бы.
В общем `undefined` точно нужно отфильтровать, про `null` не знаю, возможно и его. Надо подумать.
