### ISSUE TITLE
Опциональные ключи аргументе коллбэка

### ISSUE THREAD

**Issue by dj-stormtrooper** [pasaran/descript3#12]
В коллбэках все ключи аргумента опциональные (params, context, generate_id и тд), что приводит к явному неудобству, например в params. Допустим мы объявляем у блока внешний параметр обязательным, но при этом из-за опциональности params нам приходится писать мусорные проверки с `if (params)` и подгонять тип таких params под интерфейс расширяемого блока

https://www.typescriptlang.org/play/index.html#code/JYWwDg9gTgLgBAEwKZwGZQiOByZBnAYymDBmwG4AoS5AOggCMArJAmACgG9K5e4GANhAIBrAFxxOAXwA0PPhFLAIAOzwTufLXDABDKLpDq4XHfsN44UjWYNGbqCBAnYG+nFKsBKOAF4AfJKy8rzBUl5AA

кажется если объявлены обязательные внешние параметры, то это является интерфейсом блока и не может быть ситуации, когда он легально запускается с params: undefined, поэтому они не должны быть опцинональными

**Comment by pasaran** [comment]
Да, я временно это сделал, но откачу. Там проблема вот в чем. Хотелось, чтобы типа для `Params`, `Result` выводились из `options.params`, `options.after`. Но это очень плохо работает.

```js
    ...
    after: ( { result }: { result: Result } ) => {
        ...
    }
```
вот такой код не работает, потому что у колбэка `after` пять параметров (если их не делать опциональными). И их все нужно перечислить с нужными типами (что очень громоздко).

Кажется, что единственно правильный вариант, это делать так:

```js
interface Params { ... }
interface Context { ... }
interface Result { ... }

const block: DescriptBlock< Context, Params, Result > = de.http( {
    options: {
        after: ( { result } ) => {
            ...
        },
    }
} );
```

т.е. для базовых http-блоков (типа для методов) всегда явно указывать дженерик-тип.
Вот только непонятно, достаточно ли трех параметров, или нужно 5 (Context, ParamsIn, ParamsOut, ResultIn, ResultOut).

А уже для отнаследованных все будет выводиться.

К сожалению, тайпскрипт не такой умный, как хотелось бы, и не все может вывести.

**Comment by pasaran** [comment]
Убрал опциональность.
См. [docs/typescript-examples/options.ts](примеры).

**Comment by dj-stormtrooper** [comment]
Кажется, выглядит ок)
