### ISSUE TITLE
Предложение по api: разделить result и мета-информацию

### ISSUE THREAD

**Issue by dj-stormtrooper** [pasaran/descript3#2]
Сейчас по дефолту http-блок оборачивает свою выдачу в такую структуру:

```js
{
  result: {
    status_code: 200,
    result: { foo: 1 },
    request_options: { ... },
  }
}
```

Как насчет разделить мета информацию и оригинальный ответ?

```js
{
  result: { foo: 1 },
  meta: {
    status_code: 200,
    request_options: { ... },
  }
}
```

Сейчас по факту любая работа с http приводит к добавлению `after: ({ result }) => result.result`, так как в raw-виде объект не сериализуем (из-за циклических зависимостей в таймерах) и содержит редко используемые штуки типа request_module (которые можно будет достать из `({ meta })`).

**Comment by pasaran** [comment]
Нет, это мне не нравится. Тут получается, что формат аргументов options.after и т.д. зависит от типа блока, что неправильно. Все в options универсальное, от типа блока не зависит.

Можно вернуть `meta: false` в описание http-блока.
Или же немного поправить то, что приходит в meta, чтоб оно было сериализуемо. Там только модуль, его и убрать можно.

Я пока не вижу особой проблемы в том, что везде нужно after написать.

@doochik, что думаешь?

**Comment by dj-stormtrooper** [comment]
>  Все в options универсальное, от типа блока не зависит.
а это разве критичная для нас вещь? к примеру щас есть несовпадения в апи депсов

1. de.object и остальные базовые с объявленными deps получают в коллбэки args.deps
2. внутри de.first / de.pipe блоки получают args.deps.prev
3. если не объявлены deps - в args.deps пустой объект

Мне кажется, что, добавив meta = {} для остальных блоков, у тебя сохранится апи,
просто считаем, что для этих базовых блоков метаданных пока нет (может они в дальнейшем и появятся, например индекс успешного блока в de.first)

**Comment by pasaran** [comment]
> к примеру щас есть несовпадения в апи депсов

нет, нет несовпадения.
в deps всегда приходит объект, если депсов нет, он, очевидно, пустой.
для first/pipe есть предопределенный id-шник `'prev'` и результат доступен по `deps[ id ]` как и в остальных случаях.

Да не, ты плохо продумал. Сейчас есть один результат. Что там у него внутри -- неважно. И этот результат прокидывается через цепочку before/after/error например.
Как ты из after вернешь пару result/meta? Никак.

**Comment by pasaran** [comment]
won't fix
