### ISSUE TITLE
Предложение по api: Кидать эксепшн, если у базового блока не определен block

### ISSUE THREAD

**Issue by dj-stormtrooper** [pasaran/descript3#3]
Для базовых блоков (de.http, de.object, de.func, de.array и др) необходимо поле block, но если его не определить, то блок не падает, а просто возвращает объект. Есть смысл явно валидировать это поле в апи блока

Также во второй версии была валидна такая запись

```
de.object({
  foo: block,
})
```

Если кидать эксепшен, то подобные проблемы во время миграции v2 -> v3 сразу становятся явными

**Comment by pasaran** [comment]
Ага. Норм. Сделаю.
